"""v4

Revision ID: 6d9a83cfd561
Revises: a1f4a831cf8e
Create Date: 2023-11-22 19:57:33.838562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9a83cfd561'
down_revision = 'a1f4a831cf8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surat', schema=None) as batch_op:
        batch_op.drop_column('jenis')

    with op.batch_alter_table('surat_masuk', schema=None) as batch_op:
        batch_op.drop_column('jenis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surat_masuk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('surat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
